### ISSUE TITLE
Inquiry about building a graphics research engine

### ISSUE THREAD

**Issue by lzero1115** [yoharol/ArmorerPhys#2]
Very nice work. And I would like to ask if there are any more references if I want to build my own graphics research engine like yours?

**Comment by yoharol** [comment]
Hi, thanks for the question. 
It will take a long time. My suggestion is to first try easier framework like Taichi in python, and then start with C++ framework like eigen and libigl.  When libigl is not enough, it's time to build your own. 
The import thing is, build your framework only when it is truly necessary. Don't waste too much time on building wheels in the beginning stage.
